config/routes.rb
Rails.application.routes.draw do
  get 'project_members/show'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :projects, except: :destroy do
    get "post_room", to: "projects#post_room"
    resources :project_members, only: :create
    resources :posts, only: :create
  end

  resources :pages, only: %i[show]
  resources :conversations, only: :show do
    resources :messages, only: :create
  end

  resources :project_members, only: :update
  resources :users, only: %i[index show edit update] do
    resources :conversations, only: :create
  end

  get "dashboard", to: "pages#dashboard"
end

app/models/user.rb
 class User < ApplicationRecord
  has_many :conversations
  has_many :invitor_conversations, class_name: 'Conversation', foreign_key: 'invitor_id'
  has_many :invitee_conversations, class_name: 'Conversation', foreign_key: 'invitee_id'
  has_many :messages
  has_many :project_members
  has_many :projects, through: :project_members
  has_many :initiated_projects, class_name: 'Project'

  has_many :posts
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_one_attached :photo

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # validates :username, uniqueness: { message: 'User name already taken!' }
  validates :bio, length: { in: 1..10000 }
  validates :location, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true

  def to_param
    username
  end

  def self.find_by_param(input)
    find_by_username(input)
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def accepted_member_of_project?(project)
    project_members.find_by(project: project).accepted?
  end

  def member_of_project?(project)
    projects.include?(project)
  end

  def can_apply_to_project?(project)
    !member_or_owner_of_project?(project)
  end

  def member_or_owner_of_project?(project)
    member_of_project?(project) || project.is_owner?(self)
  end

  def supporter?
    projects.count > 1
  end

  def all_rounder?
    skills_on_projects = projects.map { |project| project.skills }.flatten
    skills_on_projects.count { |skill| skills.include?(skill) } > 1
  end

  def expert?
    project_skill_names = projects.map { |project| project.skills.map(&:name) }.flatten
    skills.map(&:name).any? { |skill| project_skill_names.count(skill) > 1 }
  end

  def expert_in
    project_skill_names = projects.map { |project| project.skills.map(&:name) }.flatten
    skills.map(&:name).find { |skill| project_skill_names.count(skill) > 1 }
  end

  include PgSearch::Model
    pg_search_scope :global_search,
      against: [ :first_name, :location ],
      associated_against: {
        skills: [:name]
      },
    using: {
      tsearch: { prefix: true }
    }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :find_user, only: %i[show edit update]

  def index
    if params[:query].present?
      @users = User.global_search(params[:query])
    else
      @users = User.all
    end
  end

  def show
    @projects = Project.all
    @conversation = Conversation.find_or_initialize_by(invitor: current_user, invitee: @user)
  end

  def edit; end

  def update
    @user.update(user_params)
    redirect_to user_path(@user)
    ## status?
  end

  private

  def find_user
    @user = User.find_by_param(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :username, :bio, :location, :linkedin_url, :first_name, :last_name, :photo)
  end
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4 form-account">
      <h1>Edit your profile</h1>

      <%= simple_form_for(@user) do |f| %>
        <%= f.input :username %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :bio %>
        <%= f.input :location %>
        <%= f.input :linkedin_url %>
        <%= f.input :photo, as: :file %>
        <%= f.submit %>
      <% end %>

    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-4">
  <div class="user-index justify-content-center">
    <div class = "header-container">
      <h1>CONNECT WITH PROFESSIONALS</h1>
      <h5>Team up, resource your venture, grow your network.</h5>
    </div>
    <div class = "p-4">
      <%= form_with url: users_path, method: :get, class: "d-flex justify-content-center" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "button-input",
              placeholder: "Find a collaborator by their name, location or skill"
            %>
        <%= submit_tag "Search", class: "search-button" %>
      <% end %>
    </div>
    <%# cards %>
    <div class="index-users-cards mt-4">
      <% @users.each do |user| %>
        <%= link_to user_path(user), class: "remove-hover" do %>
          <div class="index-user-card">
            <div class="index-user-infos">
              <div class="index-user-photo">
                <%= cl_image_tag user.photo.key, class: "avatar-bordered-index" %>
              </div>
              <div class="index-user-name">
                <h3><%= user.first_name %></h3>
              </div>
              <div class="user-badges">
                <div class="user-badge">
                  <% if user.supporter? %>
                    <%= image_tag("support.png", height: "33px", width: "33px") %>

                  <% end %>
                </div>
                <div class="user-badge">
                  <% if user.all_rounder? %>
                    <%= image_tag("all_rounder.png", height: "33px", width: "33px") %>

                  <% end %>
                </div>
                <div class="user-badge">
                  <% if user.expert_in == "Web Development" %>
                    <%= image_tag("web_development.png", height: "33px", width: "33px") %>

                  <% end %>
                </div>
                <div class="user-badge">
                  <% if user.expert_in == "Graphic Design" %>
                    <%= image_tag("graphic_design.png", height: "33px", width: "33px") %>

                  <% end %>
                  <%# <%= image_tag("support", height: "22px") %>
                </div>
              </div>
            </div>
            <div class="user-card-left-col">
              <%# <div class="user-skills"> %>
                <%# <div class="skills-display"> %>
                  <% if user.skills.first %>
                    <div class="skills-first">
                      <p><%= user.skills.first.name %></p>
                    </div>
                  <% end %>
                  <% if user.skills.second %>
                    <div class="skills-second">
                      <p><%= user.skills.second.name %></p>
                    </div>
                  <% end %>
                  <% if user.skills.third %>
                    <div class="skills-third">
                      <p><%= user.skills.third.name %></p>
                    </div>
                  <% end %>
                <%# </div> %>
                <div class="index-user-photo">
                  <%# <%= cl_image_tag user.photo.key, class: "avatar-bordered" %>
                </div>
                <div class="index-user-location">
                  <h6><i class="fa-solid fa-location-dot mr-5">  </i></h6>
                  <h6><%= user.location %></h6>
                </div>
              <%# </div> %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section>
  <div class="container mt-4 mb-5">
    <div class="user-show-banner">
      <div class="user-show-banner-profile">
        <div class="user-show-avatar">
          <%= cl_image_tag @user.photo.key, class: "avatar-large" %>
        </div>
        <div class="user-title">
          <h1><%= @user.first_name %>'s Profile</h1>
          <div>
              <% if current_user == @user %>
                <%= link_to "Edit profile", edit_user_path(@user), class: "button" %>
              <% end %>
          <strong>
            </div>
            <p> <%= icon('fa-solid', 'location-dot')%> <%= @user.location %></p>
          </strong>
        </div>
      </div>
      <div class="user-show-content">
        <div class="user-skills">
          <h4>Skills</h4>
          <% @user.skills.each do |skill| %>
            <div class="skill d-flex justify-content-center align-items-center">
              <span><%= skill.name %></span>
            </div>
          <% end %>
          <div class="d-flex justify-content-center">
            <% if @conversation.persisted? %>
              <%= link_to "Message #{@user.first_name}", conversation_path(@conversation), class: "button" %>
            <% else %>
              <%= link_to "Message #{@user.first_name}", user_conversations_path(@user), data: {turbo_method: :post}, class: "button" %>
            <% end %>
          </div>
          <div class="social-icons d-flex justify-content-center align-items-center">
            <%= icon('fa-brands', 'instagram') %>
            <%= link_to @user.linkedin_url, class: 'mx-2' do %>
              <%= icon('fa-brands', 'linkedin')%>
            <% end %>
          </div>
          <h4><%= @user.first_name %>'s Badges</h4>
          <div class="badges d-flex flex-wrap justify-content-center">
            <div class="badge">
              <% if @user.supporter? %>
                <%= image_tag "support.png", height: "45px" %>
                <p>Collaborator</p>
              <% end %>
            </div>
            <div class="badge">
              <% if @user.all_rounder? %>
                <%= image_tag "all_rounder.png", height: "45px" %>
                <p>All-Rounder</p>
              <% end %>
            </div>
            <div class="badge">
              <% if @user.expert_in == "Web Development" %>
                <%= image_tag "web_development.png", height: "45px" %>
                <p>Web Development</p>
              <% end %>
            </div>
            <div class="badge">
              <% if @user.expert_in == "Graphic Design" %>
                <%= image_tag "graphic_design.png", height: "45px" %>
                <p>Graphic Design</p>
              <% end %>
            </div>
          </div>
        </div>
        <div class="user-info d-flex flex-column">
          <div class="user-about">
            <h4>About <%= @user.first_name %></h4>
            <div class="user-about-content">
              <div class="bio-icons">
                <div class=bio-text>
                  <p><%= @user.bio %></p>
                </div>
              </div>
            </div>
          </div>
          <div class="user-projects mt-2">
            <h4>Projects</h4>
            <div class="user-show-projects-index-card">
              <% if @user.initiated_projects.empty? %>
                <p><%= "#{@user.first_name} hasn't initiated any projects yet." %></p>
              <% else%>
                <h4><%= @user.first_name %> started:</h4>
                <ul>
                  <% @user.initiated_projects.each do |project| %>
                    <li><%= link_to project.title, project_path(project) %></li>
                  <% end %>
                </ul>
              <% end %>
            </div>
          </div>
          <div class="mt-auto">
            <div class="user-show-projects">
              <h4><%= @user.first_name %> collaborates on</h4>
              <div class="user-show-projects-index">
                <% @user.projects.each do |project| %>
                  <div class="user-show-projects-index-card">
                    <h4><%= project.title %></h4>
                    <%= cl_image_tag project.photos[0].key %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>