config/routes.rb
Rails.application.routes.draw do
  get 'project_members/show'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :projects, except: :destroy do
    get "post_room", to: "projects#post_room"
    resources :project_members, only: :create
    resources :posts, only: :create
  end

  resources :pages, only: %i[show]
  resources :conversations, only: :show do
    resources :messages, only: :create
  end

  resources :project_members, only: :update
  resources :users, only: %i[index show edit update] do
    resources :conversations, only: :create
  end

  get "dashboard", to: "pages#dashboard"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    MyPeople MyCommunity <i class="fa-regular fa-face-sunglasses"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <div class="d-flex">
      <div>
        <%= link_to root_path, class: "navbar-brand" do %>
          <%= image_tag "ring-logo.png" %>
        </div>
        <div class="mt-3">
          <p>My People | My Community</p>
        </div>
      <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "ADD A VENTURE", new_project_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "PROJECTS", projects_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "PEOPLE", users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">

            <% if user_signed_in? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } %>
            <% else %>
              <%= image_tag "profile_placeholder.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>

              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_projectssearchbar.html.erb
<div class = "p-4">
  <%= form_with url: projects_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "Find a project by it's name, location or social category"
                  %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/shared/_userssearchbar.html.erb
<div class = "p-4">
  <%= form_with url: users_path, method: :get, class: "d-flex" do %>
    <%= text_field_tag :query,
                    params[:query],
                    class: "form-control",
                    placeholder: "Find a collaborator by their name, location or skill"
                  %>
    <%= submit_tag "Search", class: "button" %>
  <% end %>
</div>