config/routes.rb
Rails.application.routes.draw do
  get 'project_members/show'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :projects, except: :destroy do
    get "post_room", to: "projects#post_room"
    resources :project_members, only: :create
    resources :posts, only: :create
  end

  resources :pages, only: %i[show]
  resources :conversations, only: :show do
    resources :messages, only: :create
  end

  resources :project_members, only: :update
  resources :users, only: %i[index show edit update] do
    resources :conversations, only: :create
  end

  get "dashboard", to: "pages#dashboard"
end

app/views/pages/dashboard.html.erb
<div class="container">
  <div class="container-header mt-4" >
    <div>
      <h1>Welcome to your Dashboard <%= current_user.first_name %></h1>
    </div>
    <div class="dashboard-content">
      <div class="tab-heading">
        <ul class="nav nav-pills mb-3 mt-4 justify-content-around" id="pills-tab" role="tablist">
          <li class="nav-item" role="presentation">
            <button class="nav-link active nav-red" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Your Projects</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link nav-red" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">Your Collaborations</button>
          </li>
          <li class="nav-item" role="presentation">
            <button class="nav-link nav-red" id="pills-messages-tab" data-bs-toggle="pill" data-bs-target="#pills-messages" type="button" role="tab" aria-controls="pills-messages" aria-selected="false">Your Messages</button>
          </li>
        </ul>
      </div>
      <div>
        <%# Your projects %>
        <div class="tab-content container-header" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <div class="your-projects">
              <% if current_user.initiated_projects.empty? %>
                <p>You haven't added a project yet, click</p>
                <%= link_to "here", new_project_path %>
                <p>to add your venture.</p>
              <% else %>
                <% current_user.initiated_projects.each do |project| %>
                  <h3><%= link_to project.title, project_path(project) %></h3>
                  <div class="project">
                    <% project.project_members.each do |project_member| %>
                      <div class="collaborators">
                        <%= link_to user_path(project_member.user) do %>
                          <%= cl_image_tag project_member.user.photo.key, class: "avatar-xlarge" %>
                        <% end %>
                        <span><%= project_member.user.first_name %> (<%= project_member.status %>):</span>
                        <%= link_to "Start chat", user_conversations_path(project_member.user), data: {turbo_method: :post}, class:"btn-chat"  %>
                        <span><%= status_link(project_member)%></span>
                      </div>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <%# Your Collaborations %>
          <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <% if current_user.projects.empty? %>
              <p><%= "You currently don't collaborate on any other projects" %></p>
              <p><%= link_to "Browse Ventures", projects_path %></p>
            <% else %>
              <div class="dashboard-cards">
                <% current_user.projects.each do |project|  %>
                  <div class="dashboard-card">
                    <%# <%= link_to project_path(project) do %>
                      <div class="card-image" id="banner">
                        <h4><%= project.title %></h4>
                      </div>
                      <div class="card-content">
                        <%= link_to user_conversations_path(project.user), data: {turbo_method: :post} do %>
                          <div class="card-content-items-1">
                            <p class="<%= project.status %>"> MEMBER STATUS:<%= project.status %></p>
                            <p>CONTACT <%= project.user.first_name.upcase %></p>
                          <% end %>
                          <%# <%= link_to "Start chat", user_conversations_path(project.user), data: {turbo_method: :post}, class:"btn-chat"  %>
                          <%# <div class="card-content-description"> %>
                          <%# <p><%= project.description.truncate(130) %>
                        </div>
                      </div>
                      <%# <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          </div>
          <%# messages %>
          <div class="tab-pane fade" id="pills-messages" role="tabpanel" aria-labelledby="pills-messages-tab">
            <% if @conversations.empty? %>
              <p><%= "You currently don't have any new messages or conversations" %></p>
              <p><%= link_to "Browse our community of professionals", users_path %> or <%= link_to "Browse Ventures", projects_path %> </p>
            <% else %>
              <div class="notification">
                <% @conversations.each do |conversation| %>
                  <div class="collaborator">
                    <%= cl_image_tag conversation.other_user(current_user).photo.key, class: "avatar-large" %>
                    <div class="notification-content">
                      <p><%= link_to "Chat with #{conversation.other_user(current_user).first_name}", conversation_path(conversation) %></p>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
  <div class="banner flex-container d-flex align-items-center">
    <div class="text">
      <h1>My People </h1>
      <h1>My Community</h1>
      <p> Skill share for social change </p>
    </div>
    <div
      class="banner-img-together">
    </div>
  </div>
  <div class="home-container">
    <h2> <%= link_to "Add your project", new_project_path, class: "button" %> <%= link_to "Join a venture", projects_path, class: "button" %> <%= link_to 'Build your team', users_path, class: "button" %></h2>
  </div>
<div>