config/routes.rb
Rails.application.routes.draw do
  get 'project_members/show'
  get 'users/index'
  get 'users/show'
  get 'users/edit'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :projects, except: :destroy do
    get "post_room", to: "projects#post_room"
    resources :project_members, only: :create
    resources :posts, only: :create
  end

  resources :pages, only: %i[show]
  resources :conversations, only: :show do
    resources :messages, only: :create
  end

  resources :project_members, only: :update
  resources :users, only: %i[index show edit update] do
    resources :conversations, only: :create
  end

  get "dashboard", to: "pages#dashboard"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_many :project_categories
  has_many :categories, through: :project_categories
  has_many :posts
  has_many :project_members
  has_many :users, through: :project_members
  has_many :project_skills
  has_many :skills, through: :project_skills
  has_many_attached :photos


  validates :title, presence: true
  validates :description, length: { in: 1..1000 }
  validates :location, presence: true
  validates :start_date, presence: true
  validates :end_date, presence: true

  enum status: %i[PENDING ACCEPTED DECLINED]

  include PgSearch::Model
  pg_search_scope :global_search,
    against:[
      :title,
      :description,
      :location
    ],
    associated_against: {
      categories: [:name]
    },
    using: {
      tsearch: { prefix: true }
    }


  def is_owner?(user)
    self.user == user
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @projects = Project.global_search(params[:query])
    else
      @projects = Project.all
    end
  end

  def show
    if !current_user
      redirect_to new_user_session_path, notice: "Please create an account"
    end
    ## one project's page
    @project = Project.find(params[:id])
    @project_member = ProjectMember.new
    @posts = Post.where(project_id: params[:id])
    @post = Post.new
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def post_room
    @project = Project.find(params[:project_id])
    @project_member = ProjectMember.new
    @posts = Post.where(project_id: params[:project_id])
    @post = Post.new
  end

  private

  def project_params
    params.require(:project).permit(:title, :description, :location, :start_date, :end_date, skill_ids: [], category_ids: [], photos: [])
  end
end

app/views/projects/index.html.erb
<div class="project-index">
  <div class="container text-center">
    <h1>FIND A PROJECT</h1>
    <h5>Apply your skills, grow your portfolio, help your community.</h5>
    <div class = "search-area mt-5">
      <%= form_with url: projects_path, method: :get, class: "d-flex justify-content-center" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "button-input",
              placeholder: "Find a project by it's name, location or social category"
            %>
        <%= submit_tag "Search", class: "search-button" %>
      <% end %>
    </div>
    <%# cards section %>
    <div class="project-index-cards mt-5">
      <% @projects.each do |project| %>
        <%= link_to project_path(project) do %>
          <div class="card-trip">
            <% if project.photos.first.present? %>
              <%= cl_image_tag project.photos.first.key %>
            <% else %>
              <img src="https://res.cloudinary.com/divqv7xyh/image/upload/v1668766905/production/5ouqeaddnvc0i34b4wtc3gj9u2f4.jpg" alt="project image">
            <% end %>
            <div class="card-trip-infos">
              <div>
                <h2><%= project.title %></h2>
                <div>
                  <p><%= project.description.truncate(130) %></p>
                  <% project.skills.each do |skill| %>
                  <div class="skill-pill">
                    <p><%= skill.name %></p>
                  </div>

                  <% end %>
                </div>
              </div>
              <%= cl_image_tag project.user.photo.key, class: "card-trip-user avatar-bordered"%>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container">
  <div class="form-container">
    <div class="form" id='project-form'>
    <h2>Add Your Project</h2>
    <h5 class="text-center">Resource your team, find your next collaborator, and grow your network.</h5>
      <%= simple_form_for @project do |f| %>
        <%= f.input :title, required: false%>
        <%= f.input :description, :label => "Describe the aim of this Project and some of the needed skills" %>
        <%= f.association :skills, :label => "Which skills will your project need?", as: :check_boxes, wrapper: :vertical_collection_inline, input_html: { class: "skill-pill" } %>
        <%= f.input :location, required: false %>
        <%= f.association :categories, :label => "Which categories best describes your project", as: :check_boxes, wrapper: :vertical_collection_inline, input_html: { class: "form-label category-pill" } %>
        <%= f.input :start_date, required: false, as: :date, html5: true %>
        <%= f.input :end_date, required: false, as: :date, html5: true %>
        <%= f.input :photos, as: :file, input_html: { multiple: true } %>
        <div class="d-flex justify-content-center">
          <%= f.submit "Create Project", class: "button" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/projects/post_room.html.erb
<div class="container mt-4 show-main-container">
  <div class="project-show-leftcol">
    <div class="show-image-carousel">
      <div class ="carosel-container">
        <div class="splide" role="group" aria-label="Splide Basic HTML Example" data-controller="slider">
          <div class="splide__track">
            <ul class="splide__list">
              <% @project.photos.each do |photo| %>
                <li class="splide__slide"><%= cl_image_tag photo.key, height: 500, width: 600, crop: :fill %></li>
              <%end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="show-skills">
      <h4>Categories</h4>
      <div class="tags">
        <% @project.categories.each do |category| %>
          <div class="tag category">
            <span><%= category.name %></span>
          </div>
        <% end %>
      </div>
      <h4>Skills needed</h4>
      <div class="tags">
        <% @project.skills.each do |skill| %>
          <div class="tag skill">
            <span><%= skill.name %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="project-show-rightcol">
    <div class="project-info">
      <h3><%= @project.title %></h3>
      <p><%= @project.description %></p>
    </div>
    <div class="user-info">
      <div >
        <h3>NewsFeed</h3>
        <div class="project-posts">
          <% @posts.each do |post| %>
            <div class="post-room-message">
              <%# replace image %>
              <%= cl_image_tag post.user.photo.key, class: "avatar", height: "50px" %>
              <div class="notification-content">
                <h5><%= post.user.full_name %></h5>
                <p><%= post.content %></p>
              </div>
            </div>
          <%end %>
        </div class="project-message-new">
        <%= simple_form_for [@project, @post] do |f| %>
          <%= f.input :content, required: false, label: "Share an update with your team members", input_html: { class: "mt-1" }  %>
          <div class="d-flex justify-content-between">
            <%= f.button :submit, class: "button" %>
            <%= link_to "Project Info", project_path(@project), class: "button" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<% content_for :meta_title, "#{@project.title} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @project.description %>

<div class="container mt-4 show-main-container">
  <div class="project-show-leftcol">
    <div class="show-image-carousel">
      <div class ="carosel-container">
        <div class="splide" role="group" aria-label="Splide Basic HTML Example" data-controller="slider">
          <div class="splide__track">
            <ul class="splide__list">
              <% @project.photos.each do |photo| %>
                <li class="splide__slide"><%= cl_image_tag photo.key, height: 500, width: 600, crop: :fill %></li>
              <%end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="show-skills">
      <h4>Categories</h4>
      <div class="tags">
        <% @project.categories.each do |category| %>
          <div class="tag category">
            <span><%= category.name %></span>
          </div>
        <% end %>
      </div>
      <h4>Skills needed</h4>
      <div class="tags">
        <% @project.skills.each do |skill| %>
          <div class="tag skill">
            <span><%= skill.name %></span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="project-show-rightcol">
    <div class="project-info">
      <h3><%= @project.title %></h3>
      <p><%= @project.description %></p>
      <div>
        <% if current_user.can_apply_to_project?(@project) %>
          <%= simple_form_for [@project, @project_member], class: 'mb-4' do |f| %>
            <%= f.submit 'Apply', class: "button"%>
          <% end %>
        <% end %>
      </div>
    </div>
    <div class="user-info">
      <div class="d-flex">
        <div class="user-content">
          <h3>Project Info</h3>
          <p>This project was initiated by <%= @project.user.first_name %> from <%= @project.user.location %>.</p>
          <p>"<%= @project.user.bio %>"</p>
        </div>
        <div class="user-img">
          <%= cl_image_tag (@project.user.photo.key), height: "200px" %>
        </div>
      </div>
      <div class="user-members">
        <div>
          <h4>There are <%= pluralize(@project.project_members.count, "collaborator") %> working on this venture.</h4>
        </div>
        <div class="d-flex p-2 align-items-center">
          <% @project.project_members.each do |member| %>
            <div class="member mx-2">
              <% if member.user.photo.attached? %>
                <%= cl_image_tag member.user.photo.key, class: "project-show-avatar" %>
              <% end %>
              <%= link_to user_path(member.user) do %>
                <%= member.user.first_name %>
              <% end %>
            </div>
          <% end %>
          <% if current_user.member_or_owner_of_project?(@project) %>
            <%= link_to "POSTS", project_post_room_path(@project), class: "button" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

</div>
<%# Carosel %>

app/views/projects/test.html.erb
<div class="container mt-4 show-main-container">
    <div class="project-show-leftcol">
      <div class="show-image-carousel">
        <div class ="carosel-container">
          <div class="splide" role="group" aria-label="Splide Basic HTML Example" data-controller="slider">
            <div class="splide__track">
              <ul class="splide__list">
                <% @project.photos.each do |photo| %>
                  <li class="splide__slide"><%= cl_image_tag photo.key, height: 500, width: 600, crop: :fill %></li>
                <%end %>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <div class="show-skills">
        <h4>Categories</h4>
          <div class="tags">
            <% @project.categories.each do |category| %>
              <div class="tag category">
                <span><%= category.name %></span>
              </div>
            <% end %>
          </div>
        <h4>Skills needed</h4>
          <div class="tags">
            <% @project.skills.each do |skill| %>
              <div class="tag skill">
                <span><%= skill.name %></span>
              </div>
            <% end %>
          </div>
      </div>
    </div>

    <div class="project-show-rightcol">
      <div class="project-info">
        <h3><%= @project.title %></h3>
        <p><%= @project.description %></p>
        <div>
          <% if current_user.can_apply_to_project?(@project) %>
            <%= simple_form_for [@project, @project_member], class: 'mb-4' do |f| %>
              <%= f.submit 'Apply', class: "button"%>
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="user-info">
        <div class="d-flex">
          <div class="user-content">
            <h3>Project Info</h3>
            <p>This project was initiated by <%= @project.user.first_name %> from <%= @project.user.location %>.</p>
            <p>"<%= @project.user.bio %>"</p>
          </div>
          <div class="user-img">
            <%= cl_image_tag (@project.user.photo.key), height: "200px" %>
          </div>
        </div>
        <div class="user-members">
          <div>
            <h4>There are <%= pluralize(@project.project_members.count, "collaborator") %> working on this venture.</h4>
          </div>
          <div class="p-2">
            <% @project.project_members.each do |member| %>
              <div class="d-flex">
              <% if member.user.photo.attached? %>
              <div class="member">
                <%= cl_image_tag member.user.photo.key, class: "project-show-avatar" %>
              <% end %>
              <%= link_to user_path(member.user) do %>
              <%= member.user.first_name %>
              <% end %>
              </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>



<% if current_user.initiated_projects.empty? %>
  <p><%= "You currently have not listed any ventures" %></p>
  <p><%= link_to "List a Venture", new_project_path %></p>
<% else %>
  <% current_user.initiated_projects.each do |project| %>
    <div class="dashboard-card">
      <div class="card-image" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
        <%# #Projects initiated by the user %>
      </div>
      <div class="card-content">
        <h4><%= link_to project.title, project_path(project) %></h4>
        <div class="content-header">
          <h5>Project Members:</h5>
        </div>
        <% project.project_members.each do |project_member| %>
          <div class="card-content-items">
            <p><%= project_member.user.first_name %> (<%= project_member.status %>):</p>
            <%= status_link(project_member)%>
            <%= link_to "Start chat", user_conversations_path(project_member.user), data: {turbo_method: :post}, class:"btn-chat"  %>
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>